import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
// components
import Navbar from "@components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "01 Social Network",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col lg:flex-row  min-h-screen">
          <Navbar />
          <div className="flex-1 bg-slate-100 p-6 mb-14 lg:mb-0 ml-0 md:px-8 lg:px-8 xl:px-8 2xl:px-8 lg:ml-52">
            {children} {/* Main content */}
          </div>
        </div>
      </body>
    </html>
  );
}
